name: Deployment
on: push

jobs:
  setops-stages:
    name: Detect SetOps stages based on the current branch
    runs-on: ubuntu-latest
    outputs:
      stages: ${{ steps.stages.outputs.stages }}
    if: github.ref == 'refs/heads/production' || github.ref == 'refs/heads/staging'
    steps:
      - name: "Detect SetOps stages based on the current branch"
        id: stages
        run: |
          if [ "$GITHUB_REF" == "refs/heads/staging" ]; then
            echo '::set-output name=stages::staging'
          elif [ "$GITHUB_REF" == "refs/heads/production" ]; then
            echo '::set-output name=stages::production'
          else
            echo "⚠️ Could not determine stages for $GITHUB_REF"
            exit 1
          fi

  setops-deployment:
    needs: setops-stages
    uses: setopsco/github-actions/.github/workflows/build-and-deployment-workflow.yml@v1
    with:
      setops-organization: zweitag
      setops-stages: ${{ needs.setops-stages.outputs.stages }}
      setops-apps: web job
      setops-project: hipstermaps
      predeploy-command: bin/rails db:migrate
      build-args: |
        GIT_REV=${{ github.sha }}
    secrets:
      setops-username: ${{ secrets.SETOPS_USER }}
      setops-password: ${{ secrets.SETOPS_PASSWORD }}
